INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Ahuachapán", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Apaneca", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Atiquizaya", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Concepción de Ataco", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("El Refugio", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Guaymango", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Jujutla", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("San Francisco Menéndez", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("San Lorenzo", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("San Pedro Puxtla", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Tacuba", 1);
INSERT INTO municipality(name_municipality, id_departament_municipality) VALUES ("Turin", 1);
